package:
    name: hello
    version: 0.0.1

source:
    path: ..

requirements:
    build:
        - {{compiler('c')}}
        - {{compiler('fortran')}}
        - meson
        - python
        - numpy
    host:
        - python
        - numpy

test:
    imports:
        - hello_lib
    source_files:
        - test/
    requires:
        - pytest
    commands:
        - pytest
